version: '3'
services:
  river_knowledge_postgres:
    build:
      context: postgres
      dockerfile: Dockerfile
    volumes:
      - ../initdb:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=backend
      - POSTGRES_USER=${SPRING_DATASOURCE_USER}
      - POSTGRES_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    restart: always

  river_knowledge_osmosis:
    build:
      context: .
      dockerfile: osm/Dockerfile

    environment:
      - POSTGRES_USER=${SPRING_DATASOURCE_USER}
      - POSTGRES_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - POSTGRES_DB=backend
      - POSTGRES_PORT=${POSTGRES_PORT}
      - HOST_INFO=${HOST_INFO}
      - RESULT_INFO_FILE={RESULT_INFO_FILE}
    depends_on:
      - river_knowledge_postgres